using UnityEngine;
using UnityEngine.SceneManagement;
using static Unity.Burst.Intrinsics.X86.Avx;

public class ZikiDestroying : MonoBehaviour
{
    [SerializeField] private GameObject hitMarker;
    [SerializeField] private int interval;
    [SerializeField] private GameObject myBullet;
    [SerializeField] private SpriteRenderer playerSprite;
    [SerializeField] private GameObject bomb;
    [SerializeField] private AudioClip deathSe;
    [SerializeField] private AudioClip bombSe;
    [SerializeField] private float bombVolume = 1.0f;
    //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã®å®šç¾©
    [Header("ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹")]
    [SerializeField] private int playerHP = 3;
    [SerializeField] private int bombCount = 3;
    [SerializeField] private int shotPower = 1;
    private AudioSource audioSource;
    private GameObject[] bombs = new GameObject[3];
    private GameObject hitMarkerActivating;
    bool isShiftPushing = false;
    private int kuraiFrameCounter = 0;
    bool kuraiTriggered = false;
    //bool xTriggered = false;
    bool xCoolTime = false;
    bool zikiInvulnerable = false;
    int xCoolTimeCounter = 0;
    float StartExplosion = 0;
    int mainShotCooldown = 0;
    void DestroyAllObjectsWithTag(string tag)
    {
        GameObject[] objects = GameObject.FindGameObjectsWithTag(tag); // ï¿½wï¿½ï¿½^ï¿½Oï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½æ“¾

        foreach (GameObject obj in objects) // ï¿½zï¿½ï¿½ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½×‚Äíœ
        {
            Destroy(obj);
        }
    }


    void MyBullet_create()
    {
        if (mainShotCooldown == 0)
        {
            Vector3 newPos = this.transform.position;
            Vector3 offset = new Vector3(0.25f, 0, 0);

            GameObject bullet1 = Instantiate(myBullet, newPos + offset, Quaternion.identity);
            GameObject bullet2 = Instantiate(myBullet, newPos - offset, Quaternion.identity);

            // å¼¾ã«ãƒ‘ãƒ¯ãƒ¼ã‚’ä¼ãˆã‚‹ï¼ˆBullet ã‚¹ã‚¯ãƒªãƒ—ãƒˆãŒå¿…è¦ï¼‰
            myBullet bulletScript1 = bullet1.GetComponent<myBullet>();
            myBullet bulletScript2 = bullet2.GetComponent<myBullet>();
            //if (bulletScript1 != null) bulletScript1.SetPower(shotPower);
            //if (bulletScript2 != null) bulletScript2.SetPower(shotPower);

            mainShotCooldown = interval;
        }
        else
        {
            mainShotCooldown --;
        }
    }
    void BombStart()
    {
        zikiInvulnerable = true;
        DestroyAllObjectsWithTag("bullet");
        DestroyAllObjectsWithTag("enemy");
        DestroyAllObjectsWithTag("enemyBullet");
        for (int i = 0; i < 3; i++)
        {
            float angle = i * 120f; // 120ï¿½xï¿½ï¿½ï¿½Â”zï¿½u
            bombs[i] = Instantiate(bomb, transform.position, Quaternion.identity, transform); // ï¿½ï¿½ï¿½@ï¿½Ìqï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Éİ’ï¿½
            StartExplosion++;
        }
        
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("enemyBullet"))
        {
            Destroy(collision.gameObject);
                kuraiTriggered = true;
        }
    }

    private void Start()
    {
        Vector3 playerPos = transform.position;
        hitMarkerActivating = Instantiate(hitMarker, playerPos, Quaternion.identity);
        hitMarkerActivating.SetActive(false);
        //InvokeRepeating("MyBullet_create", 0, interval);
        Debug.Log(hitMarker.transform.position);
        audioSource = GetComponent<AudioSource>();
    }
    void FixedUpdate()
    {
        //ï¿½á‘¬ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Û‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (Input.GetKey(KeyCode.LeftShift))
        {
            isShiftPushing = true;
        }
        else
        {
            isShiftPushing = false;
        }
        float zikiSpeed = isShiftPushing ? 0.11f : 0.22f; // ï¿½á‘¬ï¿½È‚ï¿½È‚ï¿½Æ‚ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½È‚ñ‚¿‚ï¿½ï¿½
        //ï¿½Ú“ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.UpArrow))
        {
            transform.Translate(0, zikiSpeed, 0);
        }
        if (Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.LeftArrow))
        {
            transform.Translate(-zikiSpeed, 0, 0);
        }
        if (Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.DownArrow))
        {
            transform.Translate(0, -zikiSpeed, 0);
        }
        if (Input.GetKey(KeyCode.D) || Input.GetKey(KeyCode.RightArrow))
        {
            transform.Translate(zikiSpeed, 0, 0);
        }

        if (StartExplosion>=1f&&StartExplosion <= 180f)
        {
            StartExplosion++;
        }
        if (StartExplosion > 180f)
        {
            StartExplosion = 0f;
            DestroyAllObjectsWithTag("bullet");
            DestroyAllObjectsWithTag("enemy");
            DestroyAllObjectsWithTag("enemyBullet");
        }
            //ï¿½ï¿½ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½Gï¿½ï¿½ï¿½ï¿½ï¿½@ï¿½ğ”¼“ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
            SpriteRenderer sr = GetComponent<SpriteRenderer>(); // SpriteRendererï¿½ï¿½ï¿½æ“¾
        if (sr != null)
        {
            Color newColor = sr.color;
            newColor.a = zikiInvulnerable ? 0.5f : 1f; // ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ÏX
            sr.color = newColor;
        }

        //ï¿½á‘¬ï¿½}ï¿½[ï¿½Jï¿½[ï¿½Ìï¿½ï¿½Wï¿½æ“¾ï¿½Eï¿½\ï¿½ï¿½
        Vector3 playerPos = transform.position;
        hitMarkerActivating.transform.position = playerPos;
        //ï¿½á‘¬ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Û‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (Input.GetKey(KeyCode.LeftShift))
        {
            isShiftPushing = true;
        }
        else
        {
            isShiftPushing = false;
        }
        //ï¿½{ï¿½ï¿½ï¿½Nï¿½[ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½Û‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
        if (xCoolTime&& xCoolTimeCounter<=250)
        {
            xCoolTimeCounter++;
        }
        if (xCoolTimeCounter> 250)
        {
            xCoolTime = false;
            xCoolTimeCounter = 0;
            zikiInvulnerable = false;
        }


        if (isShiftPushing) // Shiftï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½
        {
            hitMarkerActivating.SetActive(true);// ï¿½ï¿½ï¿½ï¿½ï¿½Û‚ï¿½\ï¿½ï¿½
        }
        else
        {
            hitMarkerActivating.SetActive(false); // ï¿½Êíï¿½Í”ï¿½\ï¿½ï¿½
        }
        if (Input.GetKey(KeyCode.Z)) // Zï¿½Lï¿½[ï¿½Å’eï¿½ï¿½ï¿½ï¿½
        {
            MyBullet_create();
        }
        if (!Input.GetKey(KeyCode.Z))
        {
            mainShotCooldown = 0;
        }
        if (Input.GetKey(KeyCode.X) && !xCoolTime && bombCount >0)// Xï¿½Lï¿½[ï¿½Åƒ{ï¿½ï¿½
        {
            BombStart();
            xCoolTime = true;
            bombCount--;
            zikiInvulnerable = true;
            audioSource.PlayOneShot(bombSe);
        }
        if (kuraiTriggered)// ï¿½ï¿½ï¿½ç‚¢ï¿½{ï¿½ï¿½ï¿½ï¿½tï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½È‚ç‰½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½
        {
            kuraiFrameCounter++;

            if (kuraiFrameCounter >= 8 && !zikiInvulnerable)
            {
                // 8ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½oï¿½ßï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡
                Vector3 position = new Vector3(-2.78f, -3.25f, 0f);
                transform.position = position;
                kuraiFrameCounter = 0; // ï¿½ï¿½ï¿½Zï¿½bï¿½g
                kuraiTriggered = false;
                xCoolTime = true;
                zikiInvulnerable = true;
                xCoolTimeCounter += 180;
                Debug.Log("æ­»äº¡");
                playerHP--;

                if (playerHP <= 0)
                {
                    Debug.Log("ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼ï¼");
                    //æ®‹æ©ŸãŒãªããªã‚‹ã¨ã‚¿ã‚¤ãƒˆãƒ«ã«ã‚‚ã©ã‚‹
                    SceneManager.LoadScene("Title");
                }

                var tmp = audioSource.volume;
                audioSource.volume = bombVolume;
                audioSource.PlayOneShot(deathSe);
                audioSource.volume = tmp;
            }
            else if (kuraiFrameCounter >= 8 && zikiInvulnerable)
            {

                kuraiFrameCounter = 0; // ï¿½ï¿½ï¿½Zï¿½bï¿½g
                kuraiTriggered = false;

                var tmp = audioSource.volume;
                audioSource.volume = bombVolume;
                audioSource.PlayOneShot(deathSe);
                audioSource.volume = tmp;
                Debug.Log("ãã‚‰ã„ãƒœãƒ æˆåŠŸ");
            }
        }
        
    }
}